# Site settings
title: elements
email: hiya@email.com
url: http://127.0.0.1:4000/
description: "elements site"
baseurl: 

# Footer settings
footer: Student | Copyright 2017 


# Build settings
markdown: kramdown
permalink: pretty